# Generated by Django 2.2.3 on 2019-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tamanho', models.CharField(choices=[('pp', 'Porte Pequeno'), ('pm', 'Porte Médio'), ('pg', 'Porte Grande')], max_length=20)),
                ('idade', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
