# Generated by Django 2.2.3 on 2019-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rePet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(choices=[('0', 'De 2 a 6 meses'), ('1', '1 Ano'), ('2', '2 anos'), ('3', '3 anos'), ('4', '4 anos'), ('5', '5 anos'), ('6', '6 anos'), ('7', '7 anos'), ('8', '8 anos')], max_length=20),
        ),
    ]
