# Generated by Django 2.2.3 on 2019-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rePet', '0003_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(choices=[('De 2 a 6 meses', 'De 2 a 6 meses'), ('1 ano', '1 ano'), ('2 anos', '2 anos'), ('3 anos', '3 anos'), ('4 anos', '4 anos'), ('5 anos', '5 anos'), ('6 anos', '6 anos'), ('7 anos', '7 anos'), ('8 anos', '8 anos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(choices=[('Porte Pequeno', 'Porte Pequeno'), ('Porte Médio', 'Porte Médio'), ('Porte Grande', 'Porte Grande')], max_length=20),
        ),
    ]
